version: "3.9"

services:

  backend:
    image: shelfcare-be:v1
    networks:
      - shelfcare-net
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    image: shelfcare-fe:v1
    networks:
      - shelfcare-net
    depends_on:
      - backend
    ports:
      - "80:80"

  postgres:
    image: postgres:15
    networks:
      - shelfcare-net
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: bookdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


networks:
  shelfcare-net:
    name: shelfcare-net
    driver: bridge
